### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by guillaume-gomez** [guillaume-gomez/SlackNotifier#1]
- [ ] create a model to store githubWehbook
- [ ] create a model to send message
- [ ] trigger Pull Request comment in a specific repository
- [ ] trigger Issue comment in a specific repository
- [ ] extend two precious objectives in organisation 
- [ ] filter by name webhook

**Comment by guillaume-gomez** [comment]
Next Step : 
Create a dashboard in the website
